# Finload Dev Setup (Windows)
# Run from PowerShell: .\scripts\setup-dev.ps1

# ! Caution: This file was mostly generated by AI.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "=== Finload Dev Setup (Windows) ===" -ForegroundColor Cyan

$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

# ── Rust ───────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "→ Checking for Rust..." -ForegroundColor Yellow
if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
    Write-Host "  Rust not found. Download and run rustup from https://rustup.rs/" -ForegroundColor Red
    Write-Host "  After installing Rust, re-run this script." -ForegroundColor Red
    exit 1
}
Write-Host "  Rust found: $(cargo --version)" -ForegroundColor Green

# ── WebView2 ───────────────────────────────────────────────────────────────────
# WebView2 is bundled with Windows 11 and recent Windows 10 builds.
# Tauri will prompt the user to install it if missing at runtime.

# ── Python venv ────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "→ Setting up Python virtual environment..." -ForegroundColor Yellow
python -m venv src-backend\.venv
& src-backend\.venv\Scripts\pip install --upgrade pip -q
& src-backend\.venv\Scripts\pip install -r src-backend\requirements.txt -q
Write-Host "  Done." -ForegroundColor Green

# ── Node packages ──────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "→ Installing Node.js packages..." -ForegroundColor Yellow
npm install
Write-Host "  Done." -ForegroundColor Green

# ── mpv ────────────────────────────────────────────────────────────────────────
# A pinned mpv build is vendored rather than installed system-wide, so every
# dev machine and CI run bundles the exact same binary -- see
# scripts/fetch-mpv-windows.mjs for why (winget/choco/scoop installs land in
# different places with different filenames depending on distributor and
# version). Needs the npm install above for 7zip-min, which the script uses
# to unpack the archive.
Write-Host ""
Write-Host "→ Vendoring mpv (required for audio playback)..." -ForegroundColor Yellow
node scripts\fetch-mpv-windows.mjs
Write-Host "  Done." -ForegroundColor Green

Write-Host ""
Write-Host "=== Setup complete! ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "To start development:"
Write-Host "  npm run dev:tauri"
